apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: saveshies.ru
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - saveshies.ru
      secretName: letsencrypt-prod
  rules:
    - host: saveshies.ru
      http:
        paths:
          - path: /
            backend:
              serviceName: saveshies
              servicePort: 80
